### ISSUE TITLE
Replace JOI with AJV

### ISSUE THREAD

**Issue by dhruvsaxena1998** [dhruvsaxena1998/node-express-typescript#15]
- Replacing JOI with AJV can be a good option as AJV has optimized schema-validator functions with JSON Schema Structure like syntax

**Comment by deepanshu2506** [comment]
hey @dhruvsaxena1998  I would like to work on this as part of hacktoberfest

**Comment by dhruvsaxena1998** [comment]
Sure, Let me know. I'm thinking to create more issues and try to add more PR myself
